#!/bin/bash
#
#

POWERSHELL=/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe

echo ""
echo "--- Starting vcXsrv if it is not running ---"
echo ""

OUT=$($POWERSHELL -command "Get-Process -name 'vcxsrv' | Format-List ProcessName" |grep "vcxsrv")
if [ -n "$OUT" ]; then
	echo ""
	echo "Info: VcXsrv already running."
	echo ""
else
	"/mnt/c/Program Files/VcXsrv/vcxsrv.exe" :0 -ac -terminate -lesspointer -multiwindow -clipboard -wgl &
	sleep 5
fi

echo ""
echo "--- Setting up XFCE Panel ---"
echo ""

# Calculate new x-position (approx middle of the screen) for XFCE panel based on screen resolution
X_RES="\s*([[:digit:]]+)x([[:digit:]]+)"
if [[ "$(xrandr 2>/dev/null | grep '*')" =~ $X_RES ]]; then
	X_POS=$(expr ${BASH_REMATCH[1]} / 2 - 60)
fi

FILE=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
sed -e "s/<property name=\"position\" type=\"string\" value=\"p=\(.\+\);x=\(.\+\);y=\(.\+\)\"\/>/<property name=\"position\" type=\"string\" value=\"p=\1;x=$X_POS;y=\3\"\/>/" $FILE >$FILE.new
mv $FILE.new $FILE

echo ""
echo "--- Preparing Windows-Linux desktop integration ---"
echo ""

echo -e ""
echo -e "--- Starting XFCE session ---"
echo -e ""
echo -e "\e[93m"
echo -e "####################################################"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###            \e[95m\e[1mDON'T CLOSE THIS WINDOW\e[21m\e[93m           ###"
echo -e "###   \e[95mIt would close all running openSUSE apps\e[93m   ###"
echo -e "###                                              ###"
echo -e "###              \e[92m\e[1mHave a lot of fun!\e[21m\e[93m              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "####################################################"
echo -e "\e[39m"
echo ""

startxfce4 >/dev/null 2>&1
