#!/bin/bash
#
#

POWERSHELL=/mnt/c/Windows/System32/WindowsPowerShell/v1.0/powershell.exe
PROFILE_DIR_WIN=$($POWERSHELL -C "Write-Host \$env:USERPROFILE")
PROFILE_DIR_LIN=$(echo "$PROFILE_DIR_WIN" | sed -e "s/^\(.\):/\/mnt\/\L\1/" -e "s/\\\/\//g")
WINDOWS_USERNAME="$(basename $PROFILE_DIR_LIN)"

echo ""
echo "--- Starting vcXsrv if it is not running ---"
echo ""

OUT=$($POWERSHELL -command "Get-Process -name 'vcxsrv' | Format-List ProcessName" |grep "vcxsrv")
if [ -n "$OUT" ]; then
	echo ""
	echo "Info: VcXsrv already running."
	echo ""
else
	"/mnt/c/Program Files/VcXsrv/vcxsrv.exe" :0 -ac -terminate -lesspointer -multiwindow -clipboard -wgl -dpi auto &
	sleep 5
fi

echo ""
echo "--- Starting PulseAudio Server ---"
echo ""
PULSEAUDIO="$PROFILE_DIR_LIN/pulseaudio-windows-11.1-32bit"

if [ -d "$PULSEAUDIO" ]; then
	echo ""
	#$PULSEAUDIO/bin/pulseaudio.exe
fi

echo ""
echo "--- Setting up XFCE Panel ---"
echo ""

# Calculate new x-position (approx middle of the screen) for XFCE panel based on screen resolution
X_RES="\s*([[:digit:]]+)x([[:digit:]]+)"
if [[ "$(xrandr 2>/dev/null | grep '*')" =~ $X_RES ]]; then
	X_POS=$(expr ${BASH_REMATCH[1]} / 2 - 60)
fi

FILE=~/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-panel.xml
sed -e "s/<property name=\"position\" type=\"string\" value=\"p=\(.\+\);x=\(.\+\);y=\(.\+\)\"\/>/<property name=\"position\" type=\"string\" value=\"p=\1;x=$X_POS;y=\3\"\/>/" $FILE >$FILE.new
mv $FILE.new $FILE

echo ""
echo "--- Preparing Windows-Linux desktop integration ---"
echo ""

BOOKMARKS_DIR=~/.config/gtk-3.0
BOOKMARKS_FILE=bookmarks
DRIVES=$(ls /mnt/)

mkdir -p $BOOKMARKS_DIR
mkdir -p ~/windows

sed -i "\|$PROFILE_DIR_LIN Windows-$WINDOWS_USERNAME\$|d" $BOOKMARKS_DIR/$BOOKMARKS_FILE
echo "file:///$PROFILE_DIR_LIN Windows-$WINDOWS_USERNAME" >>$BOOKMARKS_DIR/$BOOKMARKS_FILE
[ ! -e ~/windows/$WINDOWS_USERNAME ] && ln -s $PROFILE_DIR_LIN ~/windows


for DRIVE in $DRIVES; do
        sed -i "/\/mnt\/$DRIVE\$/d" $BOOKMARKS_DIR/$BOOKMARKS_FILE
        echo "file:///mnt/$DRIVE" >>$BOOKMARKS_DIR/$BOOKMARKS_FILE
        [ ! -e ~/windows/$DRIVE ] && ln -s /mnt/$DRIVE ~/windows
done


echo -e ""
echo -e "--- Starting XFCE session ---"
echo -e ""
echo -e "\e[93m"
echo -e "####################################################"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###            \e[95m\e[1mDON'T CLOSE THIS WINDOW\e[21m\e[93m           ###"
echo -e "###   \e[95mIt would close all running openSUSE apps\e[93m   ###"
echo -e "###                                              ###"
echo -e "###              \e[92m\e[1mHave a lot of fun!\e[21m\e[93m              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "###                                              ###"
echo -e "####################################################"
echo -e "\e[39m"
echo ""

startxfce4 >/dev/null 2>&1
